aggregator/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^', include('aggregator.www.urls', namespace='www')),
    url(r'^rss/', include('aggregator.rss.urls', namespace='rss')),
]

aggregator/www/urls.py
import django.conf.urls

import aggregator.www.views


urlpatterns = [
    django.conf.urls.url(
        r'^$',
        aggregator.www.views.index, name='index'),

    django.conf.urls.url(
        r'^tag/(?P<pk>[0-9]+)/$',
        aggregator.www.views.tag, name='tag'),
    django.conf.urls.url(
        r'^event/(?P<pk>[0-9]+)/$',
        aggregator.www.views.event, name='event'),
    django.conf.urls.url(
        r'^event/$',
        aggregator.www.views.events_list, name='events_list'),
    django.conf.urls.url(
        r'^place/(?P<pk>[0-9]+)/$',
        aggregator.www.views.place, name='place'),
    django.conf.urls.url(
        r'^place/$',
        aggregator.www.views.places_list, name='places_list'),

    django.conf.urls.url(
        r'^run_parsers$',
        aggregator.www.views.run_parsers, name='run_parsers'),
]

system/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('aggregator.urls', namespace='aggregator')),
    url(r'^admin/', include(admin.site.urls)),
]

www/urls.py
import django.conf.urls

import www.views


urlpatterns = [
    django.conf.urls.url(
        r'^$',
        www.views.index, name='index'),

    django.conf.urls.url(
        r'^tag/(?P<pk>[0-9]+)/$',
        www.views.tag, name='tag'),
    django.conf.urls.url(
        r'^event/(?P<pk>[0-9]+)/$',
        www.views.event, name='event'),
    django.conf.urls.url(
        r'^event/$',
        www.views.events_list, name='events_list'),
    django.conf.urls.url(
        r'^place/(?P<pk>[0-9]+)/$',
        www.views.place, name='place'),
    django.conf.urls.url(
        r'^place/$',
        www.views.places_list, name='places_list'),

    django.conf.urls.url(
        r'^run_parsers$',
        www.views.run_parsers, name='run_parsers'),
]

core/models.py
import django.db.models

import core.tools.enum


class Tag(django.db.models.Model):
    """
    Tags for events and places
    """
    tag = django.db.models.CharField(max_length=40)

    def __unicode__(self):
        return self.tag


####################


class EventType(core.tools.enum.Enum):
    """
    Event type enum to compact type field
    Please update manually
    Unknown types will store in EventData
    """
    unknown = 0
    other = 1

    choices = (
        (unknown, 'unknown'),
        (other, 'other'),
    )


class Event(django.db.models.Model):
    """
    Base event model

    ext_id: PARSER:EXTERNAL_ID string
    """
    ext_id = django.db.models.CharField(db_index=True, max_length=100)
    type = django.db.models.PositiveSmallIntegerField(
        choices=EventType.choices)
    #
    title = django.db.models.CharField(max_length=100)
    description = django.db.models.TextField()
    text = django.db.models.TextField()
    #
    age_restrictions = django.db.models.PositiveSmallIntegerField(
        null=True, blank=True)

    def type_str(self):
        """
        type to str via EventType
        """
        return EventType(self.type)

    def __unicode__(self):
        return '[{} : {}] ({}) {}'.format(
            self.id, self.ext_id, self.type, self.title)


class EventTags(django.db.models.Model):
    """
    Search events via tags
    """
    event = django.db.models.ForeignKey(Event)
    tag = django.db.models.ForeignKey(Tag)

    def __unicode__(self):
        return '[{}] {}'.format(
            self.event.id, self.tag.tag)


class EventImages(django.db.models.Model):
    """
    Store all event images links here
    """
    event = django.db.models.ForeignKey(Event)
    image = django.db.models.CharField(max_length=100)

    def __unicode__(self):
        return '[{}] {}'.format(
            self.event.id, self.image)


class EventData(django.db.models.Model):
    """
    Unknown event data
    Do not miss anything
    """
    event = django.db.models.ForeignKey(Event)
    key = django.db.models.CharField(max_length=20)
    value = django.db.models.CharField(max_length=100)

    def __unicode__(self):
        return '[{}] {} = {}'.format(
            self.event.id, self.key, self.value)


####################


class PlaceType(core.tools.enum.Enum):
    """
    Place type enum to compact type field
    Please update manually
    Unknown types will store in PlaceData
    """
    unknown = 0
    other = 1

    choices = (
        (unknown, 'unknown'),
        (other, 'other'),
    )


class City(django.db.models.Model):
    """
    Keep city unque and compact storage
    """
    name = django.db.models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


class Place(django.db.models.Model):
    """
    Base place model

    ext_id: PARSER:EXTERNAL_ID string
    """
    ext_id = django.db.models.CharField(db_index=True, max_length=100)
    type = django.db.models.PositiveSmallIntegerField(
        choices=PlaceType.choices)
    #
    title = django.db.models.CharField(max_length=100)
    text = django.db.models.TextField()
    #
    url = django.db.models.CharField(max_length=250)
    #
    city = django.db.models.ForeignKey(City)
    address = django.db.models.CharField(max_length=200)
    geo_latitude = django.db.models.FloatField(null=True)
    geo_longitude = django.db.models.FloatField(null=True)

    def type_str(self):
        """
        type to str via PlaceType
        """
        return PlaceType(self.type)

    def __unicode__(self):
        return '[{} : {}] ({}) {}'.format(
            self.id, self.ext_id, self.type, self.title)


class PlaceTags(django.db.models.Model):
    """
    Search places via tags
    """
    place = django.db.models.ForeignKey(Place)
    tag = django.db.models.ForeignKey(Tag)

    def __unicode__(self):
        return '[{}] {}'.format(
            self.place.id, self.tag.tag)


class PhoneType(core.tools.enum.Enum):
    """
    Phone type enum to compact type field
    Please update manually
    Unknown types will store in PlaceData
    """
    unknown = 0
    other = 1

    choices = (
        (unknown, 'unknown'),
        (other, 'other'),
    )


class PlacePhones(django.db.models.Model):
    """
    One place may have multiple phones
    """
    place = django.db.models.ForeignKey(Place)
    type = django.db.models.PositiveSmallIntegerField(
        choices=PhoneType.choices)
    phone = django.db.models.CharField(max_length=20)

    def __unicode__(self):
        return '[{}] ({}) {}'.format(
            self.place.id, self.type, self.phone)


class PlaceMetros(django.db.models.Model):
    """
    One place may be located near multiple metro stations
    """
    place = django.db.models.ForeignKey(Place)
    metro = django.db.models.CharField(max_length=30)

    def __unicode__(self):
        return '[{}] {}'.format(
            self.place.id, self.metro)


class WorkTimeType(core.tools.enum.Enum):
    """
    Work time type enum to compact type field
    Please update manually
    Unknown types will store in PlaceData
    """
    unknown = 0
    other = 1
    openhours = 2
    kassa = 3

    choices = (
        (unknown, 'unknown'),
        (other, 'other'),
        (openhours, 'openhours'),
        (kassa, 'kassa'),
    )


class PlaceWorkTimes(django.db.models.Model):
    """
    Working time by type
    For example "open hours" or "ticket office work"
    """
    place = django.db.models.ForeignKey(Place)
    type = django.db.models.PositiveSmallIntegerField(
        choices=WorkTimeType.choices)
    work_time = django.db.models.CharField(max_length=50)

    def __unicode__(self):
        return '[{}] ({}) {}'.format(
            self.place.id, self.type, self.work_time)


class PlaceImages(django.db.models.Model):
    """
    Store all place images links here
    """
    place = django.db.models.ForeignKey(Place)
    image = django.db.models.CharField(max_length=100)

    def __unicode__(self):
        return '[{}] {}'.format(
            self.place.id, self.image)


class PlaceData(django.db.models.Model):
    """
    misc keys in places
    """
    place = django.db.models.ForeignKey(Place)
    key = django.db.models.CharField(max_length=20)
    value = django.db.models.CharField(max_length=100)

    def __unicode__(self):
        return '[{}] {} = {}'.format(
            self.place.id, self.key, self.value)


####################


class Schedule(django.db.models.Model):
    """
    Event time and place
    """
    event = django.db.models.ForeignKey(Event)
    place = django.db.models.ForeignKey(Place)
    #
    date = django.db.models.DateField()
    start_time = django.db.models.TimeField(null=True, blank=True)
    end_time = django.db.models.TimeField(null=True, blank=True)

    def __unicode__(self):
        return '[{}] {} / {} : {} {}'.format(
            self.id,
            self.event.id, self.place.id,
            self.date, self.start_time)

aggregator/www/views.py
import django.shortcuts

import aggregator.models
import aggregator.parsers.controller


def index(request):
    schedule = aggregator.models.Schedule.objects.all()
    return django.shortcuts.render(
        request, 'www/index.html', {'schedule': schedule})


def tag(request, pk):
    t = aggregator.models.Tag.objects.get(pk=pk)
    return django.shortcuts.render(
        request, 'www/tag.html', {'tag': t})


def events_list(request):
    events = aggregator.models.Event.objects.all()
    return django.shortcuts.render(
        request, 'www/events_list.html', {'events': events})


def event(request, pk):
    e = aggregator.models.Event.objects.get(pk=pk)
    return django.shortcuts.render(
        request, 'www/event.html', {'event': e})


def places_list(request):
    places = aggregator.models.Place.objects.all()
    return django.shortcuts.render(
        request, 'www/places_list.html', {'places': places})


def place(request, pk):
    p = aggregator.models.Place.objects.get(pk=pk)
    return django.shortcuts.render(
        request, 'www/place.html', {'place': p})


def run_parsers(request):
    statuses = aggregator.parsers.controller.Controller.run()
    return django.shortcuts.render(
        request, 'www/run_parsers.html', {'statuses': statuses})

www/views.py
import django.shortcuts

import core.models
import parsers.controller


def index(request):
    schedule = core.models.Schedule.objects.all()
    return django.shortcuts.render(
        request, 'www/index.html', {'schedule': schedule})


def tag(request, pk):
    t = core.models.Tag.objects.get(pk=pk)
    return django.shortcuts.render(
        request, 'www/tag.html', {'tag': t})


def events_list(request):
    events = core.models.Event.objects.all()
    return django.shortcuts.render(
        request, 'www/events_list.html', {'events': events})


def event(request, pk):
    e = core.models.Event.objects.get(pk=pk)
    return django.shortcuts.render(
        request, 'www/event.html', {'event': e})


def places_list(request):
    places = core.models.Place.objects.all()
    return django.shortcuts.render(
        request, 'www/places_list.html', {'places': places})


def place(request, pk):
    p = core.models.Place.objects.get(pk=pk)
    return django.shortcuts.render(
        request, 'www/place.html', {'place': p})


def run_parsers(request):
    statuses = parsers.controller.Controller.run()
    return django.shortcuts.render(
        request, 'www/run_parsers.html', {'statuses': statuses})

templates/www/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>Aggregator</title>

        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    </head>

    <body style="padding-top: 70px;">

        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'www:index' %}">Aggregator</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'www:events_list' %}">Events</a></li>
                        <li><a href="{% url 'www:places_list' %}">Places</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'www:run_parsers' %}">Parse NOW</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">

            <div class='trains'>

                <p id="errors" class="bg-danger" style="padding: 20px; display:none;"></p>

                <h1>Aggregator</h1>

                {% block content %}{% endblock content %}

            </div>

        </div>

        <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

        {% block scripts %}{% endblock scripts %}

    </body>
</html>

templates/www/event.html
{% extends "www/base.html" %}

{% block content %}

    <h2>{{ event.title }}</h2>

    <h4>Type: {{ event.type_str }}</h4>

    {% if event.description %}
        <p><i>Description:{{ event.description }}</i></p>
    {% endif %}

    <p>
    {% for tag in event.eventtags_set.all %}
        <span><a href="{% url 'www:tag' tag.tag.id %}">#{{ tag.tag.tag }}</a></span>
    {% endfor %}
    </p>

    <p>{{ event.text }}</p>

    <table id="table" class="table table-striped">
        <tr>
            <th>Key</th>
            <th>Value</th>
        </tr>
        {% for data in event.eventdata_set.all %}
            <tr>
            <td>{{ data.key }}</td>
            <td>{{ data.value }}</td>
            </tr>
        {% endfor %}
    </table>

    <p><i>id: {{ event.id }} / ext_id: {{ event.ext_id }}</i></p>

{% endblock %}

templates/www/events_list.html
{% extends "www/base.html" %}

{% block content %}

    <h2>Events</h2>

    <table id="table" class="table table-striped">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Description</th>
            <th>Type</th>
        </tr>
        {% for ev in events %}
            <tr>
            <td>{{ ev.id }}</td>
            <td><a href="{% url 'www:event' ev.id %}">{{ ev.title }}</a></td>
            <td>{{ ev.description }}</td>
            <td>{{ ev.type_str }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/www/index.html
{% extends "www/base.html" %}

{% block content %}

    <h2>Schedule</h2>

    <table id="table" class="table table-striped">
        <tr>
            <th>#</th>
            <th>Event</th>
            <th>Place</th>
            <th>Date</th>
            <th>Start time</th>
            <th>End time</th>
        </tr>
        {% for sch in schedule %}
            <tr>
            <td>{{ sch.id }}</td>
            <td><a href="{% url 'www:event' sch.event.id %}">{{ sch.event.title }}</a></td>
            <td><a href="{% url 'www:place' sch.place.id %}">{{ sch.place.title }}</a></td>
            <td>{{ sch.date }}</td>
            <td>{{ sch.start_time }}</td>
            <td>{{ sch.end_time }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/www/place.html
{% extends "www/base.html" %}

{% block content %}

    <h2>{{ place.title }}</h2>

    <h4>Type: {{ place.type_str }}</h4>

    <h4>{{ place.city.name }}</h4>

    <p>Address: {{ place.address }}</p>

    <ul>
    {% for metro in place.placemetros_set.all %}
        <li>{{ metro.metro }}</li>
    {% endfor %}
    </ul>

    <ul>
    {% for phone in place.placephones_set.all %}
        <li>{{ phone.phone }}</li>
    {% endfor %}
    </ul>

    <p>
    {% for tag in place.placetags_set.all %}
        <span><a href="{% url 'www:tag' tag.tag.id %}">#{{ tag.tag.tag }}</a></span>
    {% endfor %}
    </p>

    <p>{{ place.text }}</p>

    <p><a href="{{ place.url }}" target=_blank>URL</a><p>

    <table id="table" class="table table-striped">
        <tr>
            <th>Key</th>
            <th>Value</th>
        </tr>
        {% for data in place.placedata_set.all %}
            <tr>
            <td>{{ ed.key }}</td>
            <td>{{ ed.value }}</td>
            </tr>
        {% endfor %}
    </table>

    <p><i>id: {{ event.id }} / ext_id: {{ event.ext_id }}</i></p>

{% endblock %}

templates/www/places_list.html
{% extends "www/base.html" %}

{% block content %}

    <h2>Places</h2>

    <table id="table" class="table table-striped">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>City</th>
            <th>Type</th>
        </tr>
        {% for pl in places %}
            <tr>
            <td>{{ pl.id }}</td>
            <td><a href="{% url 'www:place' pl.id %}">{{ pl.title }}</a></td>
            <td>{{ pl.city.name }}</td>
            <td>{{ pl.type_str }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/www/tag.html
{% extends "www/base.html" %}

{% block content %}

    <h2>Tag: {{ tag.tag }}</h2>

    <h4>Events<h4>
    <table id="table" class="table table-striped">
        <tr>
            <th>#</th>
            <th>Title</th>
        </tr>
        {% for tag in tag.eventtags_set.all %}
            <tr>
            <td>{{ tag.tag.id }}</td>
            <td><a href="{% url 'www:event' tag.event.id %}">{{ tag.event.title }}</a></td>
            </tr>
        {% endfor %}
    </table>

    <h4>Places<h4>
    <table id="table" class="table table-striped">
        <tr>
            <th>#</th>
            <th>Title</th>
        </tr>
        {% for tag in tag.placetags_set.all %}
            <tr>
            <td>{{ tag.tag.id }}</td>
            <td><a href="{% url 'www:place' tag.place.id %}">{{ tag.place.title }}</a></td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}